wolframscript -f phase1.wls
wolframscript -f phase2.wls
wolframscript -f phase3.wls
wolframscript -f phase4.wls
wolframscript -f phase5.wls
wolframscript -f phase6.wls
wolframscript -f phase7.wls
wolframscript -f phase8.wls
wolframscript -f phase9.wls
wolframscript -f phase10.wls
wolframscript -f phase11.wls
wolframscript -f phase12.wls
wolframscript -f phase13.wls
wolframscript -f phase14.wls
wolframscript -f phase15.wls
wolframscript -f phase16.wls
wolframscript -f phase17.wls
wolframscript -f phase18.wls
wolframscript -f phase19.wls
wolframscript -f phase20.wls
wolframscript -f phase21.wls
wolframscript -f phase22.wls
wolframscript -f phase23.wls
wolframscript -f phase24.wls
wolframscript -f phase25.wls
wolframscript -f phase26.wls
wolframscript -f phase27.wls
wolframscript -f phase28.wls
wolframscript -f phase29.wls
wolframscript -f phase30.wls
wolframscript -f phase31.wls
wolframscript -f phase32.wls
wolframscript -f phase33.wls
wolframscript -f phase34.wls
wolframscript -f phase35.wls
wolframscript -f phase36.wls
wolframscript -f phase37.wls
wolframscript -f phase38.wls
wolframscript -f phase39.wls
wolframscript -f phase40.wls
wolframscript -f phase41.wls
wolframscript -f phase42.wls
wolframscript -f phase43.wls
wolframscript -f phase44.wls
wolframscript -f phase45.wls
